
server:
  port: 8876

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: product-module
  zipkin:
    base-url: http://192.168.19.10:9411/
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: 192.168.19.12
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
apple:
  price: 12
